package constans;

public class Constants {
        public final static String SOLUTIONS_BUTTON = "//a[@class='nav-link dropdown-toggle']";
        public final static String AIRFLOW_FOOTER_BUTTON= "//footer[@class='page-footer font-small blue pt-4']//*[text()='Airflow & Temperature Control']";
        public final static String PLANT_WATERING_FOOTER_BUTTON= "//ul[@class='list-unstyled']//*[text()='Plant Watering']";
        public final static String ROOF_FOOTER_BUTTON= "//ul[@class='list-unstyled']//*[text()='Roof & Gutter Deicing']";
        public final static String LIGHT_FOOTER_BUTTON= "//ul[@class='list-unstyled']//*[text()='Light & Outlet Control']";
        public final static String HOME_SECURITY_FOOTER_BUTTON= "//ul[@class='list-unstyled']//*[text()='Home Security']";
        public final static String SMART_INTEGRATION_FOOTER_BUTTON= "//ul[@class='list-unstyled']//*[text()='Smart Integration']";
        public final static String CONTACT_FOOTER_BUTTON= "//li[text()='Contact']";
        public final static String OUR_TEAM_FOOTER_BUTTON= "//ul[@class='list-unstyled']//*[text()='Our Team']";
        public final static String BOARD_OF_ADVISORS_FOOTER_BUTTON= "//ul[@class='list-unstyled']//*[text()='Board of Advisors']";
        public final static String CAREER_FOOTER_BUTTON= "//ul[@class='list-unstyled']//*[text()='Career']";
        public final static String PRESS_KIT_FOOTER_BUTTON= "//ul[@class='list-unstyled']//*[text()='Press Kit']";
        public final static String COPYRIGHT_FOOTER_BUTTON= "//ul[@class='list-unstyled']//*[text()='Copyright Statement']";
        public final static String PRIVACY_FOOTER_BUTTON= "//ul[@class='list-unstyled']//*[text()='Privacy Policy']";
        public final static String LOGO_FOOTER_ICON= "//footer[@class='page-footer font-small blue pt-4']//div[@class='footer-logo']";
        public final static String LOGO_FOOTER_MINISIZE= "//footer[@class='page-footer font-small blue pt-4']//div[@class='footer-logo mb-3']";
        public final static String FACEBOOK_FOOTER_ICON= "//div[@class='social-media']//div[1]";
        public final static String TWITTER_FOOTER_ICON= "//div[@class='social-media']//div[2]";
        public final static String INSTAGRAM_FOOTER_ICON= "//div[@class='social-media']//div[3]";
        public final static String LINKEDIN_FOOTER_ICON= "//div[@class='social-media']//div[4]";
        public final static String FACEBOOK_TITLE= "//div[@class='bi6gxh9e aov4n071']//*[text()='Ceotech Inc.']";
        public final static String TWITTER_TITLE= "//span[text()='Ceotech Inc.']";
        public final static String INSTAGRAM_TITLE= "//h1[@class='rhpdm'][text()='Ceotech Inc.']";
        public final static String LINKEDIN_TITLE= "//h1[@title='Ceotech Inc.']";
        public final static String LOGO_ALL_PAGES= "//img[@class='navbar-brand-img logo']";
        public final static String SMART_INTEGRATION_ICON= "//div[@class='col-6 smarthome-welcome-img']//*[@data-tip='Smart Integration']";
        public final static String SMART_INTEGRATION_MINISIZE= "//img[@class='img-fluid smart_integration_welcome_icon']";
        public final static String AIRFLOW_ICON= "//div[@class='col-6 smarthome-welcome-img']//*[@data-tip='Airflow and Temperature Control']";
        public final static String AIRFLOW_ICON_MINISIZE= "//img[@class='img-fluid airflow_welcome_icon']";
        public final static String PLANT_WATERING_ICON= "//div[@class='col-6 smarthome-welcome-img']//*[@data-tip='Plant Watering']";
        public final static String PLANT_WATERING_MINISIZE= "//img[@class='img-fluid watering_welcome_icon']";
        public final static String ROOF_GUTTER_ICON= "//div[@class='col-6 smarthome-welcome-img']//*[@data-tip='Roof and<br/>Gutter Deicing']";
        public final static String ROOF_GUTTER_MINISIZE= "//img[@class='img-fluid deicing_welcome_icon']";
        public final static String LIGHT_OUTLET_ICON= "//div[@class='col-6 smarthome-welcome-img']//*[@data-tip='Light and Outlet Control']";
        public final static String LIGHT_OUTLET_MINISIZE= "//img[@class='img-fluid light_welcome_icon']";
        public final static String HOME_SECURITY_ICON= "//div[@class='col-6 smarthome-welcome-img']//*[@data-tip='Home Security']";
        public final static String HOME_SECURITY_MINISIZE= "//img[@class='img-fluid security_welcome_icon']";
        public final static String OUR_TEAM_TITLE= "//h2[@class='font-weight-bold text-left'][text()='Our team']";
        public final static String OUR_TEAM_MINI_TITLE= "//h3[@class='font-weight-bold text-left'][text()='Our team']";
        public final static String BOARD_OF_ADVISORS_TITLE= "//h2[@class='font-weight-bold text-left'][text()='Board of Advisors']";
        public final static String CAREER_TITLE= "//h2[@class='font-weight-bold text-left'][text()='Career at Ceotech Inc.']";
        public final static String CONTACT_PAGE_TITLE = "//h1[text()='Contact Us']";
        public final static String CONTACT_MINI_PAGE_TITLE = "//h2[text()='Contact Us']";
        public final static String COPYRIGHT_MINI_PAGE_TITLE = "//h2[text()='Ceotech Inc. Copyright Statement']";
        public final static String SMART_PAGE_TITLE = "//h1[text()='Smart Integration']";
        public final static String SMART_MINI_PAGE_TITLE = "//h2[text()='Smart Integration']";
        public final static String ROOF_PAGE_TITLE = "//h1[text()='Roof and Gutter Deicing']";
        public final static String ROOF_MINI_PAGE_TITLE = "//h2[text()='Roof and Gutter Deicing']";
        public final static String PLANT_PAGE_TITLE = "//h1[text()='Plant Watering']";
        public final static String PLANT_MINI_PAGE_TITLE = "//h2[text()='Plant Watering']";
        public final static String LIGHT_PAGE_TITLE = "//h1[text()='Light and Outlet Control']";
        public final static String LIGHT_MINI_PAGE_TITLE = "//h2[text()='Light and Outlet Control']";
        public final static String HOME_SECURITY_PAGE_TITLE = "//h1[text()='Home Security']";
        public final static String HOME_SECURITY_MINI_PAGE_TITLE = "//h2[text()='Home Security']";
        public final static String AIRFLOW_PAGE_TITLE = "//h1[text()='Airflow and Temperature Control']";
        public final static String AIRFLOW_MINI_PAGE_TITLE = "//h2[text()='Airflow and Temperature Control']";
        public final static String ABOUT_PAGE_TITLE = "//h1[text()='About the company']";
        public final static String ABOUT_MINI_PAGE_TITLE = "//h2[text()='About the company']";
        public final static String MAIN_PAGE_TITLE = "//h1[text()='SmartHome']";
        public final static String TOGGLE_MENU = "//span[@class='navbar-toggler-icon']";
}
